import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * NO RAW COLOUR IN APPLICATION CODE.
 *
 * The palette was a locked decision with nothing behind it — the tokens existed
 * and nothing failed if you typed a hex. This closes that gap, and it goes in
 * BEFORE the landing map rather than after: the map is the surface most likely
 * to acquire ad-hoc colour (biggest, paints to canvas, and the one place "just
 * this one hex for the haze" feels reasonable). A rule added afterwards is a
 * cleanup; added first, the drift never gets written.
 *
 * Enforced only on the app's own TS/TSX. Deliberate exemptions, written down so
 * nobody has to guess and nobody reaches for a blanket disable:
 *
 *   1. `app/styles/tokens/*.css` — the token files ARE the palette. CSS is not
 *      parsed by ESLint anyway, so this is exemption by construction: hexes
 *      live in exactly one place and that place is the contract.
 *
 *   2. `docs/design/checkitdown-map-3d.html` — standalone HTML/JS painting
 *      extruded massing to a canvas. Canvas fills cannot always take a CSS
 *      variable, so it is outside the linted globs by design. When that module
 *      is wired into the app, the wrapper must read the tokens ONCE at init via
 *      `readToken()` in lib/tokens.ts and hold them in JS — never re-type the
 *      hex. An exemption written down beats a rule everyone disables.
 */
const COLOUR_MESSAGE =
  "No raw colour in app code — use a --cid-* token from app/styles/tokens/colors.css. "
  + "For canvas or any API that cannot take a CSS variable, read it once at init with "
  + "readToken() from lib/tokens.ts. See eslint.config.mjs for the written exemptions.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["app/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}", "components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          // #rgb / #rrggbb / #rrggbbaa anywhere in a string literal
          selector: "Literal[value=/#[0-9a-fA-F]{3}([0-9a-fA-F]{3}([0-9a-fA-F]{2})?)?\\b/]",
          message: COLOUR_MESSAGE,
        },
        {
          // rgb() / rgba() / hsl() / hsla() in a string literal
          selector: "Literal[value=/(rgb|hsl)a?\\s*\\(/]",
          message: COLOUR_MESSAGE,
        },
        {
          // the same, hidden inside a template literal
          selector: "TemplateElement[value.raw=/#[0-9a-fA-F]{3}([0-9a-fA-F]{3}([0-9a-fA-F]{2})?)?\\b|(rgb|hsl)a?\\s*\\(/]",
          message: COLOUR_MESSAGE,
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored Claude Design export — an artifact we consume, not code we
    // maintain. Its inline styles are the DESIGN's source of truth and are
    // meant to carry raw colour; linting it would produce noise nobody acts on
    // and would push someone toward disabling the colour rule wholesale.
    "docs/**",
    // Supabase CLI runtime scratch. Gitignored, regenerated by `supabase start`.
    "supabase/.temp/**",
    // VENDORED MAPLIBRE WORKER. Generated verbatim from node_modules by
    // scripts/sync-map-worker.mjs and hash-checked against the installed
    // package — editing it is a bug, not a fix. Minified, it produced 1076 of
    // the 1077 warnings `npm run lint` emitted, which is the same as emitting
    // none: a gate nobody can read is a gate nobody reads.
    "public/maplibre-gl-*.mjs",
  ]),
]);

export default eslintConfig;
