-- THE CENSUS: every column test:mixed is capable of moving.
--
-- Read before the suite and again after; the gate is a DIFF, not a set of
-- expected numbers. Baselines change every time a floor visit lands, and a
-- hardcoded one goes stale silently — the failure this project keeps finding.
--
-- Verification is per FACT, not per room. `rooms.verified_at` alone was the
-- old check, and it is NULL on all seventeen rooms while 6 games, 33 rakes,
-- 30 amenity rows and 2 formats carry real stamps: a broken rollback could
-- have wiped every one of them and reported a clean database.
--
-- ADD A ROW HERE whenever a scenario learns to touch a new column.
--
-- COUNTS ALONE CANNOT SEE A STAMP THAT MOVED. The receipt-date scenario
-- deliberately shifts one verification stamp from row A to row B — a
-- mis-restore that put it back on the wrong row would leave every count
-- identical and pass this gate silently, which is the plausible-output class
-- this file exists to catch. So each table also reports a CHECKSUM over its
-- rows' identity and stamps. Counts stay because they are what a human reads
-- when the checksum fails.
--
-- THE CHECKSUMS ARE NOT CONSTANTS. Row ids are regenerated by `supabase db
-- reset`, so every hash here changes across a reset and means nothing on its
-- own. This file is only ever read TWICE IN ONE RUN and diffed against itself.
select 'rooms.verified',        (count(*) filter (where verified_at is not null))::text      from rooms
union all
select 'rooms.total',           (count(*))::text                                             from rooms
union all
select 'games.verified',        (count(*) filter (where verified_at is not null))::text      from cash_games
union all
select 'games.rake_verified',   (count(*) filter (where rake_verified_at is not null))::text from cash_games
union all
select 'games.total',           (count(*))::text                                             from cash_games
union all
select 'amenities.verified',    (count(*) filter (where verified_at is not null))::text      from room_amenities
union all
select 'amenities.available',   (count(*) filter (where available))::text                    from room_amenities
union all
select 'amenities.total',       (count(*))::text                                             from room_amenities
union all
select 'house_rules.verified',  (count(*) filter (where verified_at is not null))::text      from house_rules
union all
select 'house_rules.total',     (count(*))::text                                             from house_rules
union all
select 'formats.verified',      (count(*) filter (where verified_at is not null))::text      from room_formats
union all
select 'waitlist.total',        (count(*))::text                                             from room_waitlist
union all
-- The checksums. `md5` of the ordered per-row identity + stamps, so a stamp
-- that lands back on the wrong row fails even though nothing was lost.
select 'ck.games', md5(string_agg(id || '|' || coalesce(verified_at::text,'') || '|'
     || coalesce(rake_verified_at::text,'') || '|' || coalesce(source_url,'') || '|'
     || coalesce(rake_source_url,''), E'\n' order by id)) from cash_games
union all
select 'ck.amenities', md5(string_agg(room_id || '|' || amenity_id || '|' || available
     || '|' || coalesce(verified_at::text,''), E'\n' order by room_id, amenity_id)) from room_amenities
union all
select 'ck.rooms', md5(string_agg(id || '|' || coalesce(verified_at::text,''), E'\n' order by id)) from rooms
union all
select 'ck.formats', md5(coalesce(string_agg(room_id || '|' || slug || '|'
     || coalesce(verified_at::text,''), E'\n' order by room_id, slug), '')) from room_formats
union all
select 'ck.house_rules', md5(coalesce(string_agg(room_id || '|' || label || '|'
     || coalesce(verified_at::text,''), E'\n' order by room_id, label), '')) from house_rules
order by 1;
