import { installQrSvg } from '@/lib/install-qr'

/**
 * THE QR CODE, AS A ROUTE THAT IS RENDERED ONCE AT BUILD TIME.
 *
 * Three ways to put this on the page, and the reasons the other two lost:
 *
 *   A THIRD-PARTY IMAGE URL is one line and it is the wrong line. It makes the
 *   page that asks a reader to trust us depend on somebody else's uptime, and
 *   it tells that somebody which of our readers is looking at our install page.
 *   `lib/qr.ts` argues that at length; the short version is that a privacy leak
 *   on a trust page is not a trade worth a line of code.
 *
 *   A COMMITTED FILE in `public/` — generated by a script, checked in — works,
 *   and this repo already knows what it costs. `public/maplibre-gl-worker.mjs`
 *   is exactly that shape and needed `scripts/sync-map-worker.mjs`, a prebuild
 *   step AND a `check:worker` CI gate to stop it drifting from its source. The
 *   drift there was silent and cost weeks. Buying the same problem for a
 *   picture of a URL would be a poor trade.
 *
 *   A ROUTE, PRERENDERED. `dynamic = 'force-static'` means Next renders this
 *   during `next build` and serves the bytes from disk afterwards — so it costs
 *   what a static file costs at request time, while the URL it encodes is still
 *   read from `lib/install.ts` in code. There is no second copy to drift, and
 *   no sync gate to write. That is what shipped.
 *
 * ONE CACHING TRAP, NAMED: the service worker treats every `.svg` as a shell
 * asset and caches it, and its cache name is a constant. So if `SITE_URL` ever
 * changes, an already-installed reader keeps the old QR until the worker's
 * VERSION string is bumped. That is true of the icons already; it is written
 * down here because a QR pointing at a dead host fails silently and looks fine.
 */

/* Rendered at build time and served as bytes thereafter. */
export const dynamic = 'force-static'

export function GET(): Response {
  return new Response(installQrSvg(), {
    headers: {
      'Content-Type': 'image/svg+xml; charset=utf-8',
      /* A day at the edge. The bytes change only when the site's own address
         does, which is a deploy. */
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  })
}
